.class public final Lkotlinx/android/parcel/Parceler$DefaultImpls;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lkotlinx/android/parcel/Parceler;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "DefaultImpls"
.end annotation


# direct methods
.method public static constructor <clinit>()V
    .registers 1

    const v0, 0xa5598

    invoke-static {v0}, Lcom/bytedance/covode/number/Covode;->recordClassIndex(I)V

    return-void
.end method

.method public static newArray(Lkotlinx/android/parcel/Parceler;I)[Ljava/lang/Object;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlinx/android/parcel/Parceler<",
            "TT;>;I)[TT;"
        }
    .end annotation

    .prologue
    .line 33619968
    new-instance p0, Lkotlin/NotImplementedError;

    .line 33619970
    const-string p1, "Generated by Android Extensions automatically"

    .line 33619972
    invoke-direct {p0, p1}, Lkotlin/NotImplementedError;-><init>(Ljava/lang/String;)V

    .line 33619975
    throw p0
.end method
